// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlgorithmInfo() {
  return window['go']['main']['App']['AlgorithmInfo']();
}

export function CreateAlgorithm(arg1, arg2) {
  return window['go']['main']['App']['CreateAlgorithm'](arg1, arg2);
}

export function CreateObjectives(arg1, arg2) {
  return window['go']['main']['App']['CreateObjectives'](arg1, arg2);
}

export function CreateProblem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProblem'](arg1, arg2, arg3, arg4, arg5);
}

export function ObjectivesInfo() {
  return window['go']['main']['App']['ObjectivesInfo']();
}

export function ProblemInfo() {
  return window['go']['main']['App']['ProblemInfo']();
}

export function Result() {
  return window['go']['main']['App']['Result']();
}

export function RunAlgorithm() {
  return window['go']['main']['App']['RunAlgorithm']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
