// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddConstraints(arg1:Array<main.ConstraintInput>):Promise<void>;

export function AlgorithmInfo():Promise<any>;

export function ConstraintsInfo():Promise<main.ConstraintsConfigResponse>;

export function CreateAlgorithm(arg1:main.AlgorithmInput):Promise<void>;

export function CreateObjectives(arg1:Array<main.ObjectiveInput>):Promise<void>;

export function CreateProblem(arg1:main.ProblemInput):Promise<void>;

export function ObjectivesInfo():Promise<main.ObjectiveConfigResponse>;

export function ProblemInfo():Promise<any>;

export function Result():Promise<void>;

export function RunAlgorithm():Promise<void>;

export function SelectFile():Promise<string>;

export function ShowAllInfo():Promise<void>;
