// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConstraints(arg1) {
  return window['go']['main']['App']['AddConstraints'](arg1);
}

export function AlgorithmInfo() {
  return window['go']['main']['App']['AlgorithmInfo']();
}

export function ConstraintsInfo() {
  return window['go']['main']['App']['ConstraintsInfo']();
}

export function CreateAlgorithm(arg1) {
  return window['go']['main']['App']['CreateAlgorithm'](arg1);
}

export function CreateObjectives(arg1) {
  return window['go']['main']['App']['CreateObjectives'](arg1);
}

export function CreateProblem(arg1) {
  return window['go']['main']['App']['CreateProblem'](arg1);
}

export function ObjectivesInfo() {
  return window['go']['main']['App']['ObjectivesInfo']();
}

export function ProblemInfo() {
  return window['go']['main']['App']['ProblemInfo']();
}

export function Result() {
  return window['go']['main']['App']['Result']();
}

export function RunAlgorithm() {
  return window['go']['main']['App']['RunAlgorithm']();
}

export function SaveChartImage(arg1) {
  return window['go']['main']['App']['SaveChartImage'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
