// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlgorithmInfo():Promise<void>;

export function CreateAlgorithm(arg1:string,arg2:any):Promise<void>;

export function CreateObjectives(arg1:Array<string>,arg2:Array<any>):Promise<void>;

export function CreateProblem(arg1:string,arg2:any):Promise<void>;

export function ObjectivesInfo():Promise<void>;

export function ProblemInfo():Promise<void>;

export function Result():Promise<void>;

export function RunAlgorithm():Promise<void>;

export function SelectFile():Promise<string>;
